#config.yaml

destination:
  paths:
    - "C:\\Users\\OSATPP IL\\Desktop\\111"
    - "C:\\Users\\OSATPP IL\\Desktop\\1111"

sources:
  - name: "Abakarov_m"
    path: "\\\\Abakarov_m\\РАБОТА"
  - name: "Israpilov_m"
    path: "\\\\desktop-hshsuuu\\Работа"
