#config.yaml

destination:
  path: "./synced"

sources:
  - name: "Zidan"
    path: "\\\\KOMP\\Users\\Zidan\\OOP"
  - name: "Abakarov_m"
    path: "\\\\Abakarov_m\\РАБОТА"
  - name: "Israpilov_m"
    path: "\\\\desktop-hshsuuu\\Работа"