# config.yaml

destination_root: "./synced"  # Путь на сервере, куда будут копироваться файлы
shared_folders:
  "192.168.0.101": "/mnt/shared/101"  # Путь на сервере для первой машины
  "192.168.0.102": "/mnt/shared/102"  # Путь для второй машины
