#config.yaml

destination:
  paths:
    - "C:\\Users\\OSATPP IL\\Desktop\\111"
    - "C:\\Users\\OSATPP IL\\Desktop\\1111"

sources:
  - name: "Abakarov_m"
    path: "\\\\Abakarov_m\\РАБОТА"
    buro: "БП"
  - name: "Israpilov_m"
    path: "\\\\desktop-hshsuuu\\Работа"
    buro: "ТБ"
  - name: 'Mukhtarov_z'
    path: "\\\\zubayr\\РАБОТА"
    buro: "ТБ"