version: "3"
services:
  sync-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - TG_BOT_TOKEN=your_telegram_token
      - TG_CHAT_ID=your_chat_id
    command: python entrypoint.py --web
